resolver: lts-8.2

packages:
- '.'
- examples

extra-deps:
- distributed-process-client-server-0.1.3.2
- distributed-process-extras-0.2.1.2
- distributed-process-async-0.2.3
- distributed-static-0.3.5.0
